### ISSUE TITLE
Vul de readme aan of schrijf een wiki over de update procedure.

### ISSUE THREAD

**Issue by SanderDevisscher** [inbo/fis-reports#7]
@Fhuysent ik herinner me vaag dat je een readme ging schrijven waarin beschreven werd hoe je de homepage moest updaten. Blijkbaar is dit nog niet gebeurd.

**Comment by SanderDevisscher** [comment]
@Fhuysent mag ik je aandacht hier nog eens op vestigen ?

**Comment by Fhuysent** [comment]
Uiteindelijk toe gekomen. Omdat het enkel Readme was direct in master aangepast, maar kijk gerust eens na. Geen PR dus maar als je akkoord bent kun je deze issue afsluiten. [https://github.com/inbo/fis-reports/blob/master/README.md](url)

**Comment by SanderDevisscher** [comment]
Ziet er goed uit.
